/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import controlador.ControladorTerceraLey;

import modelo.ModeloTerceraLey;            

/**
 *
 * @author whiteHat
 */
public class VistaTerceraLey extends javax.swing.JFrame {

    /**
     * Creates new form VIstaConversiones
     */
    public VistaTerceraLey() {
        initComponents();
        ModeloTerceraLey modelo = new ModeloTerceraLey(this);
        ControladorTerceraLey controlador = new ControladorTerceraLey(modelo);
        setControlador(controlador); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoMetros = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMetros = new javax.swing.JTextField();
        btnCalcularCM = new javax.swing.JButton();
        lblResultadoCentimetros = new javax.swing.JLabel();
        dialogoPulgadas = new javax.swing.JDialog();
        txtPulgada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCalcularPulgada = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblResultadoPulgadas = new javax.swing.JLabel();
        dialogoKmh = new javax.swing.JDialog();
        txtKilometro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCalcularKmh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblResultadoMps1 = new javax.swing.JLabel();
        dialogoKilogramosALibras = new javax.swing.JDialog();
        txtKilogramo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCalcularKilogramo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblResultadoKilogramo = new javax.swing.JLabel();
        dialogoCelsiusaFahrenheit = new javax.swing.JDialog();
        txtCelsius = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCalcularCelsius = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblResultadoCelsius = new javax.swing.JLabel();
        dialogoLitrosAGalones = new javax.swing.JDialog();
        txtLitros = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCalcularLitros = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblResultadoLitros = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNewtons = new javax.swing.JTextField();
        txtObjetoA = new javax.swing.JTextField();
        txtObjetoB = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDirección = new javax.swing.JComboBox<>();
        lblResultadoAccionYReaccion = new javax.swing.JLabel();
        btnCalcularAccionYReaccion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Metros a Centimetros");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel2.setText("Metros");

        txtMetros.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtMetros.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCalcularCM.setText("Calcular");
        btnCalcularCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCMActionPerformed(evt);
            }
        });

        lblResultadoCentimetros.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblResultadoCentimetros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoCentimetros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dialogoMetrosLayout = new javax.swing.GroupLayout(dialogoMetros.getContentPane());
        dialogoMetros.getContentPane().setLayout(dialogoMetrosLayout);
        dialogoMetrosLayout.setHorizontalGroup(
            dialogoMetrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoMetrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoMetrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultadoCentimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoMetrosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularCM)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogoMetrosLayout.setVerticalGroup(
            dialogoMetrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoMetrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(dialogoMetrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularCM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lblResultadoCentimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtPulgada.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtPulgada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPulgada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulgadaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pulgadas a Centimetros");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCalcularPulgada.setText("Calcular");
        btnCalcularPulgada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPulgadaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setText("Metros");

        lblResultadoPulgadas.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblResultadoPulgadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoPulgadas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dialogoPulgadasLayout = new javax.swing.GroupLayout(dialogoPulgadas.getContentPane());
        dialogoPulgadas.getContentPane().setLayout(dialogoPulgadasLayout);
        dialogoPulgadasLayout.setHorizontalGroup(
            dialogoPulgadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPulgadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoPulgadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPulgadasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogoPulgadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPulgadasLayout.createSequentialGroup()
                                .addComponent(txtPulgada, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcularPulgada)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPulgadasLayout.createSequentialGroup()
                                .addComponent(lblResultadoPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dialogoPulgadasLayout.setVerticalGroup(
            dialogoPulgadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPulgadasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoPulgadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPulgada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularPulgada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultadoPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtKilometro.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtKilometro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKilometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilometroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Kilómetros por hora a Millas por hora");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCalcularKmh.setText("Calcular");
        btnCalcularKmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularKmhActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel4.setText("km/h");

        lblResultadoMps1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblResultadoMps1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoMps1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dialogoKmhLayout = new javax.swing.GroupLayout(dialogoKmh.getContentPane());
        dialogoKmh.getContentPane().setLayout(dialogoKmhLayout);
        dialogoKmhLayout.setHorizontalGroup(
            dialogoKmhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoKmhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoKmhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoKmhLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogoKmhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoKmhLayout.createSequentialGroup()
                                .addComponent(txtKilometro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcularKmh)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoKmhLayout.createSequentialGroup()
                                .addComponent(lblResultadoMps1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dialogoKmhLayout.setVerticalGroup(
            dialogoKmhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoKmhLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoKmhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKilometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularKmh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultadoMps1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtKilogramo.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtKilogramo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKilogramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilogramoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Kilogramos a Libras");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCalcularKilogramo.setText("Calcular");
        btnCalcularKilogramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularKilogramoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel9.setText("Kilogramos");

        lblResultadoKilogramo.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblResultadoKilogramo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoKilogramo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dialogoKilogramosALibrasLayout = new javax.swing.GroupLayout(dialogoKilogramosALibras.getContentPane());
        dialogoKilogramosALibras.getContentPane().setLayout(dialogoKilogramosALibrasLayout);
        dialogoKilogramosALibrasLayout.setHorizontalGroup(
            dialogoKilogramosALibrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoKilogramosALibrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoKilogramosALibrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoKilogramosALibrasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogoKilogramosALibrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogoKilogramosALibrasLayout.createSequentialGroup()
                                .addComponent(lblResultadoKilogramo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(dialogoKilogramosALibrasLayout.createSequentialGroup()
                                .addComponent(txtKilogramo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnCalcularKilogramo)
                                .addGap(50, 50, 50))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dialogoKilogramosALibrasLayout.setVerticalGroup(
            dialogoKilogramosALibrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoKilogramosALibrasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoKilogramosALibrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKilogramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularKilogramo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultadoKilogramo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtCelsius.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtCelsius.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelsiusActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Celsius a Fahrenheit");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCalcularCelsius.setText("Calcular");
        btnCalcularCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCelsiusActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel11.setText("celsius");

        lblResultadoCelsius.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblResultadoCelsius.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoCelsius.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dialogoCelsiusaFahrenheitLayout = new javax.swing.GroupLayout(dialogoCelsiusaFahrenheit.getContentPane());
        dialogoCelsiusaFahrenheit.getContentPane().setLayout(dialogoCelsiusaFahrenheitLayout);
        dialogoCelsiusaFahrenheitLayout.setHorizontalGroup(
            dialogoCelsiusaFahrenheitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoCelsiusaFahrenheitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoCelsiusaFahrenheitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoCelsiusaFahrenheitLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogoCelsiusaFahrenheitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoCelsiusaFahrenheitLayout.createSequentialGroup()
                                .addComponent(lblResultadoCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoCelsiusaFahrenheitLayout.createSequentialGroup()
                                .addComponent(txtCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnCalcularCelsius)
                                .addGap(50, 50, 50))))))
        );
        dialogoCelsiusaFahrenheitLayout.setVerticalGroup(
            dialogoCelsiusaFahrenheitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoCelsiusaFahrenheitLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoCelsiusaFahrenheitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularCelsius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultadoCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtLitros.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtLitros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLitrosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Litros a Galones");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCalcularLitros.setText("Calcular");
        btnCalcularLitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularLitrosActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel13.setText("litros");

        lblResultadoLitros.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblResultadoLitros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoLitros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dialogoLitrosAGalonesLayout = new javax.swing.GroupLayout(dialogoLitrosAGalones.getContentPane());
        dialogoLitrosAGalones.getContentPane().setLayout(dialogoLitrosAGalonesLayout);
        dialogoLitrosAGalonesLayout.setHorizontalGroup(
            dialogoLitrosAGalonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoLitrosAGalonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoLitrosAGalonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoLitrosAGalonesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogoLitrosAGalonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoLitrosAGalonesLayout.createSequentialGroup()
                                .addComponent(lblResultadoLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoLitrosAGalonesLayout.createSequentialGroup()
                                .addComponent(txtLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnCalcularLitros)
                                .addGap(50, 50, 50))))))
        );
        dialogoLitrosAGalonesLayout.setVerticalGroup(
            dialogoLitrosAGalonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoLitrosAGalonesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoLitrosAGalonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularLitros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultadoLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("     Tercera Ley: Acción y Reacción");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jTextArea2.setRows(2);
        jTextArea2.setText("Introduce los datos del objeto A que aplica una fuerza sobre \nel objeto B. El sistema mostrará la fuerza de reacción que \nejerce B sobre A.");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel14.setText("Fuerza Aplicada por A sobre B");

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel15.setText("Dirección de la Fuerza");

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel16.setText("Nombre u objeto A");

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel17.setText("Nombre u objeto B");

        txtNewtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewtonsActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel18.setText("N");

        txtDirección.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Derecha", "Izquierda", "Arriba", "Abajo" }));
        txtDirección.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecciónActionPerformed(evt);
            }
        });

        lblResultadoAccionYReaccion.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblResultadoAccionYReaccion.setToolTipText("");
        lblResultadoAccionYReaccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCalcularAccionYReaccion.setText("calcular");
        btnCalcularAccionYReaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAccionYReaccionActionPerformed(evt);
            }
        });

        btnSalir.setText("Atrás");

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel19.setText("Resultado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(txtObjetoA))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDirección, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNewtons)
                                            .addComponent(txtObjetoB))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCalcularAccionYReaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jSeparator2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(lblResultadoAccionYReaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNewtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDirección, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtObjetoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularAccionYReaccion))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtObjetoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultadoAccionYReaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularCMActionPerformed

    private void btnCalcularPulgadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPulgadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularPulgadaActionPerformed

    private void txtPulgadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulgadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulgadaActionPerformed

    private void txtKilometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilometroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometroActionPerformed

    private void btnCalcularKmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularKmhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularKmhActionPerformed

    private void txtKilogramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilogramoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilogramoActionPerformed

    private void btnCalcularKilogramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularKilogramoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularKilogramoActionPerformed

    private void txtCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelsiusActionPerformed

    private void btnCalcularCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularCelsiusActionPerformed

    private void txtLitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLitrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLitrosActionPerformed

    private void btnCalcularLitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularLitrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularLitrosActionPerformed

    private void txtNewtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewtonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewtonsActionPerformed

    private void txtDirecciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecciónActionPerformed

    private void btnCalcularAccionYReaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAccionYReaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularAccionYReaccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTerceraLey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTerceraLey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTerceraLey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTerceraLey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTerceraLey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcularAccionYReaccion;
    public javax.swing.JButton btnCalcularCM;
    public javax.swing.JButton btnCalcularCelsius;
    public javax.swing.JButton btnCalcularKilogramo;
    public javax.swing.JButton btnCalcularKmh;
    public javax.swing.JButton btnCalcularLitros;
    public javax.swing.JButton btnCalcularPulgada;
    public javax.swing.JButton btnSalir;
    public javax.swing.JDialog dialogoCelsiusaFahrenheit;
    public javax.swing.JDialog dialogoKilogramosALibras;
    public javax.swing.JDialog dialogoKmh;
    public javax.swing.JDialog dialogoLitrosAGalones;
    public javax.swing.JDialog dialogoMetros;
    public javax.swing.JDialog dialogoPulgadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    public javax.swing.JLabel lblResultadoAccionYReaccion;
    public javax.swing.JLabel lblResultadoCelsius;
    public javax.swing.JLabel lblResultadoCentimetros;
    public javax.swing.JLabel lblResultadoKilogramo;
    public javax.swing.JLabel lblResultadoLitros;
    public javax.swing.JLabel lblResultadoMps1;
    public javax.swing.JLabel lblResultadoPulgadas;
    public javax.swing.JTextField txtCelsius;
    public javax.swing.JComboBox<String> txtDirección;
    public javax.swing.JTextField txtKilogramo;
    public javax.swing.JTextField txtKilometro;
    public javax.swing.JTextField txtLitros;
    public javax.swing.JTextField txtMetros;
    public javax.swing.JTextField txtNewtons;
    public javax.swing.JTextField txtObjetoA;
    public javax.swing.JTextField txtObjetoB;
    public javax.swing.JTextField txtPulgada;
    // End of variables declaration//GEN-END:variables
    public void setControlador(ControladorTerceraLey c) {
        btnCalcularAccionYReaccion.addActionListener(c);
        btnSalir.addActionListener(c);
    }
}
